postgres: &postgres
  adapter: postgres
  database: history_store
  schema: event_store
  host: localhost
  port: 5432
  username: nexia
  password: Password1
  encoding: UTF-8
  pool: 100
  reconnect: true

vertica: &vertica
  adapter: vertica
  database: history_store
  schema: event_store
  host: #see note in EventStore for getting the host ip of your vm
  username: dbadmin
  password: password

table_name: events

redis:
  host: localhost
  driver: hiredis
  db: 15

development:
  postgres:
    <<: *postgres
  vertica:
    <<: *vertica

test:
  postgres:
    <<: *postgres
    database: history_store
    schema: es_test
  vertica:
    <<: *vertica
    database: history_store
    schema: es_test
